const data = [
  {
    "name": "freeCodeCamp",
    "owner": "freeCodeCamp",
    "fullname": "freeCodeCamp~freeCodeCamp",
    "description": "The https://freeCodeCamp.com open source codebase and curriculum. Learn to code and help nonprofits.",
    "avatar": "https://avatars0.githubusercontent.com/u/9892522?v=4",
    "url": "https://github.com/freeCodeCamp/freeCodeCamp",
    "pushed": "2017-07-30T19:27:08Z",
    "created": "2014-12-24T17:49:19Z",
    "size": 30916,
    "stars": 290987,
    "forks": 12465,
    "topics": [
      "careers",
      "certification",
      "community",
      "curriculum",
      "d3",
      "education",
      "javascript",
      "learn-to-code",
      "math",
      "nodejs",
      "nonprofits",
      "programming",
      "react",
      "teachers"
    ],
    "language": "JavaScript",
    "watchers": 8555
  },
  {
    "name": "bootstrap",
    "owner": "twbs",
    "fullname": "twbs~bootstrap",
    "description": "The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.",
    "avatar": "https://avatars0.githubusercontent.com/u/2918581?v=4",
    "url": "https://github.com/twbs/bootstrap",
    "pushed": "2017-07-31T11:21:02Z",
    "created": "2011-07-29T21:19:00Z",
    "size": 100188,
    "stars": 113272,
    "forks": 52706,
    "topics": [
      "bootstrap",
      "css",
      "css-framework",
      "html",
      "javascript",
      "jekyll-site",
      "scss"
    ],
    "language": "JavaScript",
    "watchers": 7033
  },
  {
    "name": "free-programming-books",
    "owner": "EbookFoundation",
    "fullname": "EbookFoundation~free-programming-books",
    "description": ":books: Freely available programming books",
    "avatar": "https://avatars0.githubusercontent.com/u/14127308?v=4",
    "url": "https://github.com/EbookFoundation/free-programming-books",
    "pushed": "2017-07-26T20:32:17Z",
    "created": "2013-10-11T06:50:37Z",
    "size": 4093,
    "stars": 89703,
    "forks": 22560,
    "topics": [
      "books",
      "education",
      "list",
      "resource"
    ],
    "language": "",
    "watchers": 6668
  },
  {
    "name": "react",
    "owner": "facebook",
    "fullname": "facebook~react",
    "description": "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
    "avatar": "https://avatars3.githubusercontent.com/u/69631?v=4",
    "url": "https://github.com/facebook/react",
    "pushed": "2017-07-31T03:00:01Z",
    "created": "2013-05-24T16:15:54Z",
    "size": 124456,
    "stars": 72394,
    "forks": 13618,
    "topics": [],
    "language": "JavaScript",
    "watchers": 4778
  },
  {
    "name": "d3",
    "owner": "d3",
    "fullname": "d3~d3",
    "description": "Bring data to life with SVG, Canvas and HTML. :bar_chart::chart_with_upwards_trend::tada:",
    "avatar": "https://avatars1.githubusercontent.com/u/1562726?v=4",
    "url": "https://github.com/d3/d3",
    "pushed": "2017-07-20T02:21:42Z",
    "created": "2010-09-27T17:22:42Z",
    "size": 41545,
    "stars": 66670,
    "forks": 17437,
    "topics": [
      "visualization"
    ],
    "language": "JavaScript",
    "watchers": 3353
  },
  {
    "name": "tensorflow",
    "owner": "tensorflow",
    "fullname": "tensorflow~tensorflow",
    "description": "Computation using data flow graphs for scalable machine learning",
    "avatar": "https://avatars1.githubusercontent.com/u/15658638?v=4",
    "url": "https://github.com/tensorflow/tensorflow",
    "pushed": "2017-07-31T08:56:21Z",
    "created": "2015-11-07T01:19:20Z",
    "size": 116757,
    "stars": 65234,
    "forks": 31867,
    "topics": [
      "deep-learning",
      "deep-neural-networks",
      "distributed",
      "machine-learning",
      "ml",
      "neural-network",
      "python",
      "tensorflow"
    ],
    "language": "C++",
    "watchers": 5775
  },
  {
    "name": "You-Dont-Know-JS",
    "owner": "getify",
    "fullname": "getify~You-Dont-Know-JS",
    "description": "A book series on JavaScript. @YDKJS on twitter.",
    "avatar": "https://avatars1.githubusercontent.com/u/150330?v=4",
    "url": "https://github.com/getify/You-Dont-Know-JS",
    "pushed": "2017-07-29T07:30:34Z",
    "created": "2013-11-16T02:37:24Z",
    "size": 7167,
    "stars": 64490,
    "forks": 10780,
    "topics": [
      "async",
      "book",
      "book-series",
      "closures",
      "education",
      "es2015",
      "es6",
      "javascript",
      "learn-to-code",
      "programming",
      "prototypes",
      "training-materials",
      "training-providers"
    ],
    "language": "JavaScript",
    "watchers": 3606
  },
  {
    "name": "awesome",
    "owner": "sindresorhus",
    "fullname": "sindresorhus~awesome",
    "description": ":sunglasses: Curated list of awesome lists",
    "avatar": "https://avatars1.githubusercontent.com/u/170270?v=4",
    "url": "https://github.com/sindresorhus/awesome",
    "pushed": "2017-07-31T10:38:30Z",
    "created": "2014-07-11T13:42:37Z",
    "size": 580,
    "stars": 62754,
    "forks": 7887,
    "topics": [
      "awesome",
      "awesome-list",
      "lists",
      "resources",
      "unicorns"
    ],
    "language": "",
    "watchers": 4075
  },
  {
    "name": "vue",
    "owner": "vuejs",
    "fullname": "vuejs~vue",
    "description": "A progressive, incrementally-adoptable JavaScript framework for building UI on the web.",
    "avatar": "https://avatars1.githubusercontent.com/u/6128107?v=4",
    "url": "https://github.com/vuejs/vue",
    "pushed": "2017-07-28T23:32:56Z",
    "created": "2013-07-29T03:24:51Z",
    "size": 20075,
    "stars": 61830,
    "forks": 8716,
    "topics": [
      "framework",
      "frontend",
      "javascript",
      "vue"
    ],
    "language": "JavaScript",
    "watchers": 3530
  },
  {
    "name": "oh-my-zsh",
    "owner": "robbyrussell",
    "fullname": "robbyrussell~oh-my-zsh",
    "description": "A delightful community-driven (with 1,000+ contributors) framework for managing your zsh configuration. Includes 200+ optional plugins (rails, git, OSX, hub, capistrano, brew, ant, php, python, etc), over 140 themes to spice up your morning, and an auto-update tool so that makes it easy to keep up with the latest updates from the community.",
    "avatar": "https://avatars2.githubusercontent.com/u/257?v=4",
    "url": "https://github.com/robbyrussell/oh-my-zsh",
    "pushed": "2017-07-29T20:34:26Z",
    "created": "2009-08-28T18:15:37Z",
    "size": 4120,
    "stars": 56892,
    "forks": 12794,
    "topics": [
      "productivity",
      "shell",
      "terminal",
      "theme",
      "zsh-configuration"
    ],
    "language": "Shell",
    "watchers": 2019
  },
  {
    "name": "angular.js",
    "owner": "angular",
    "fullname": "angular~angular.js",
    "description": "AngularJS - HTML enhanced for web apps!",
    "avatar": "https://avatars3.githubusercontent.com/u/139426?v=4",
    "url": "https://github.com/angular/angular.js",
    "pushed": "2017-07-30T21:53:31Z",
    "created": "2010-01-06T00:34:37Z",
    "size": 88673,
    "stars": 56607,
    "forks": 28267,
    "topics": [],
    "language": "JavaScript",
    "watchers": 4423
  },
  {
    "name": "javascript",
    "owner": "airbnb",
    "fullname": "airbnb~javascript",
    "description": "JavaScript Style Guide",
    "avatar": "https://avatars3.githubusercontent.com/u/698437?v=4",
    "url": "https://github.com/airbnb/javascript",
    "pushed": "2017-07-29T01:00:50Z",
    "created": "2012-11-01T23:13:50Z",
    "size": 2260,
    "stars": 56254,
    "forks": 10851,
    "topics": [
      "arrow-functions",
      "es2015",
      "es6",
      "eslint",
      "javascript",
      "linting",
      "naming-conventions",
      "style-guide",
      "style-linter",
      "styleguide"
    ],
    "language": "JavaScript",
    "watchers": 2647
  },
  {
    "name": "gitignore",
    "owner": "github",
    "fullname": "github~gitignore",
    "description": "A collection of useful .gitignore templates",
    "avatar": "https://avatars1.githubusercontent.com/u/9919?v=4",
    "url": "https://github.com/github/gitignore",
    "pushed": "2017-07-31T08:42:40Z",
    "created": "2010-11-08T20:17:14Z",
    "size": 1398,
    "stars": 52958,
    "forks": 22912,
    "topics": [
      "git",
      "gitignore"
    ],
    "language": "",
    "watchers": 2135
  },
  {
    "name": "Font-Awesome",
    "owner": "FortAwesome",
    "fullname": "FortAwesome~Font-Awesome",
    "description": "The iconic font and CSS toolkit",
    "avatar": "https://avatars0.githubusercontent.com/u/1505683?v=4",
    "url": "https://github.com/FortAwesome/Font-Awesome",
    "pushed": "2017-07-17T16:07:58Z",
    "created": "2012-02-17T14:19:43Z",
    "size": 35801,
    "stars": 51624,
    "forks": 9062,
    "topics": [],
    "language": "HTML",
    "watchers": 1296
  },
  {
    "name": "react-native",
    "owner": "facebook",
    "fullname": "facebook~react-native",
    "description": "A framework for building native apps with React.",
    "avatar": "https://avatars3.githubusercontent.com/u/69631?v=4",
    "url": "https://github.com/facebook/react-native",
    "pushed": "2017-07-31T11:38:24Z",
    "created": "2015-01-09T18:10:16Z",
    "size": 139363,
    "stars": 51600,
    "forks": 12088,
    "topics": [],
    "language": "JavaScript",
    "watchers": 3132
  },
  {
    "name": "electron",
    "owner": "electron",
    "fullname": "electron~electron",
    "description": "Build cross platform desktop apps with JavaScript, HTML, and CSS",
    "avatar": "https://avatars1.githubusercontent.com/u/13409222?v=4",
    "url": "https://github.com/electron/electron",
    "pushed": "2017-07-31T10:05:15Z",
    "created": "2013-04-12T01:47:36Z",
    "size": 30747,
    "stars": 48612,
    "forks": 6117,
    "topics": [
      "c-plus-plus",
      "chrome",
      "css",
      "electron",
      "html",
      "javascript",
      "nodejs",
      "v8"
    ],
    "language": "C++",
    "watchers": 2267
  },
  {
    "name": "linux",
    "owner": "torvalds",
    "fullname": "torvalds~linux",
    "description": "Linux kernel source tree",
    "avatar": "https://avatars0.githubusercontent.com/u/1024025?v=4",
    "url": "https://github.com/torvalds/linux",
    "pushed": "2017-07-31T10:17:51Z",
    "created": "2011-09-04T22:48:12Z",
    "size": 1884927,
    "stars": 47473,
    "forks": 17851,
    "topics": [],
    "language": "C",
    "watchers": 5687
  }
]

export default data;
